#################################################################################
#                           BASIC CONFIGURATION                                 #
#################################################################################

homeassistant:
  name: Home
  latitude: 50.6634
  longitude: 3.0529699999999593
  elevation: 25
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

recorder:
  db_url: !secret db_access

history:

http:
  base_url: maoutin.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #ip_ban_enabled: True
  #login_attempts_threshold: 20
  api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

system_health:

input_datetime:
  heure_rechauffage_sdb:
    name: Heure du début du réchauffage de la SDB
    has_date: false
    has_time: true

# View all events in a logbook
# logbook:

# Include iframe in left drawer
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://hassio.local:3218

# Log of events
logger:
  logs:
    homeassistant.components: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

plant:
  citronnier:
    sensors:
      moisture: sensor.mi_flora_1_moisture
      battery: sensor.mi_flora_1_battery
      temperature: sensor.mi_flora_1_temperature
      conductivity: sensor.mi_flora_1_conductivity
      brightness: sensor.mi_flora_1_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 8
    max_temperature: 35
    min_brightness: 4000
    max_brightness: 65000

#################################################################################
#                       DEVICES AND INTEGRATIONS                                #
#################################################################################

# Media
media_extractor: # Media extractor, used to cast media with a service

media_player:

# Notifications
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key

# Hub
rfxtrx:
  device: /dev/ttyUSB0

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    track_new_devices: no
    interval_seconds: 30
    exclude:
      - 192.168.1.30

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_aqara_key
      mac: 78:11:DC:B7:E4:40

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret


#################################################################################
#                                   INCLUDES                                    #
#################################################################################

binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
