#################################################################################
#                           BASIC CONFIGURATION                                 #
#################################################################################

homeassistant:
  name: Home
  latitude: 50.6634309
  longitude: 3.0507688
  elevation: 23
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

recorder:
  db_url: !secret db_access

http:
  base_url: maoutin.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #ip_ban_enabled: True
  #login_attempts_threshold: 20
  api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.flower_power_temperature_sensor
      - sensor.flower_power_battery_level
      - sensor.flower_power_fertilizer_sensor
      - sensor.flower_power_humidity_sensor
      - sensor.flower_power_light_sensor
      - sensor.flower_power_watering_sensor
      - sensor.xiaomi_switch_new
      - sensor.xiaomi_switch_old
      - sensor.yweather_temperature_min
      - sensor.yweather_temperature_max
      - sensor.yw_day3_temperature_min
      - sensor.yw_day2_temperature_min
      - sensor.yw_day1_temperature_min
      - sensor.yw_day3_temperature_max
      - sensor.yw_day2_temperature_max
      - sensor.yw_day1_temperature_max

# View all events in a logbook
# logbook:

# Include iframe in left drawer
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://hassio.local:3218
  terminal:
    title: Terminal
    icon: mdi:console
    url: https://hassio.local:7681

# Log of events
logger:
  logs:
    homeassistant.components: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: 'fr'

# Cloud
cloud:

weather:
  - platform: yweather

#################################################################################
#                       DEVICES AND INTEGRATIONS                                #
#################################################################################

# Media
media_extractor: # Media extractor, used to cast media with a service

media_player:
#  - platform: spotify
#    client_id: 39edb7ec9c87422784f04f81fc34b6ea
#    client_secret: !secret spotify_api_key

# Notifications
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key

# Automation
ifttt:
  key: !secret ifttt_api_key

# Hub
rfxtrx:
  device: /dev/ttyUSB0

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    track_new_devices: yes
    interval_seconds: 20
    exclude:
      - 192.168.1.30
#  - platform: bluetooth_tracker

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_aqara_key
      mac: 78:11:DC:B7:E4:40


#fan:
#  - platform: template
#    fans:
#      ventilateur_salle_de_bains:
#        friendly_name: "Ventilateur salle de bains"
#        value_template: "{{ states('switch.lampe7') }}"
#        turn_on:
#          service: script.1538133008927
#        turn_off:
#          service: script.1538133067280


#################################################################################
#                                   INCLUDES                                    #
#################################################################################

binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
