#################################################################################
#                           BASIC CONFIGURATION                                 #
#################################################################################

homeassistant:
  name: Home
  latitude: 50.6634309
  longitude: 3.0507688
  elevation: 23
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes:
    test:
      # Main colors
      primary-color: 'rgba(50, 77, 103, 1)'         # Header
      accent-color: 'rgba(20, 142, 153, 1)'         # Accent color
      dark-primary-color: 'rgba(36, 58, 82, 1)'     # Hyperlinks
      light-primary-color: 'rgba(97, 125, 152, 1)'  # Horizontal line in about
      # Text colors
      primary-text-color: 'rgba(16, 42, 66, 1)'      # Primary text colour, here is referencing dark-primary-color
      text-primary-color: 'rgba(255, 255, 255, 1)'   # Primary text colour
      secondary-text-color: 'rgba(130, 154, 176, 1)' # For secondary titles in more info boxes etc.
      disabled-text-color: 'rgba(218, 226, 236, 1)'  # Disabled text colour
      # Background colors
      primary-background-color: 'rgba(241, 245, 248, 1)'   # Settings background
      secondary-background-color: 'rgba(241, 245, 248, 1)' # Main card UI background
      sidebar-background-color: 'rgba(241, 245, 248, 1)'
      divider-color: 'rgba(0, 0, 0, .12)'                  # Divider
      # Table rows
      table-row-background-color: 'rgba(241, 245, 248, 1)' # Table row
      table-row-alternative-background-color: 'rgba(228, 234, 241, 1)' # Table row alternative
      # Nav Menu
      paper-listbox-color: 'rgba(16, 42, 66, 1)'                       # Navigation menu selection hoover
      paper-listbox-background-color: 'rgba(241, 245, 248, 1)'         # Navigation menu background
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#414A59'                             # Navigation menu selection
      # Paper card
      paper-card-header-color: 'var(--accent-color)'  # Card header text colour
      paper-card-background-color: '#FFF'             # Card background colour
      paper-dialog-background-color: '#FFF'           # Card dialog background colour
      paper-item-icon-color: 'var(--accent-color)'    # Icon color
      paper-item-icon-active-color: '#F9C536'         # Icon color active
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#434954'# Popup item select
      paper-tabs-selection-bar-color: 'green'
      # Labels
      label-badge-red: 'var(--google-red-500)'
      label-badge-blue: 'var(--accent-color)'             # References the brand colour label badge border
      ha-label-badge-color: 'var(--accent-color)'
      label-badge-text-color: 'var(--primary-text-color)' # Now same as label badge border but that's a matter of taste
      label-badge-background-color: 'rgba(241, 245, 248, 1)'  # Same, but can also be set to transparent here
      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      # Google colors
      google-red-500: '#db3236'
      google-green-500: '#39E949'

# Enables configuration UI
config:

recorder:
  db_url: !secret db_access

http:
  base_url: maoutin.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #ip_ban_enabled: True
  #login_attempts_threshold: 20
  api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

input_datetime:
  heure_rechauffage_sdb:
    name: Heure du début du réchauffage de la SDB
    has_date: false
    has_time: true

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.flower_power_temperature_sensor
      - sensor.flower_power_battery_level
      - sensor.flower_power_fertilizer_sensor
      - sensor.flower_power_humidity_sensor
      - sensor.flower_power_light_sensor
      - sensor.flower_power_watering_sensor
      - sensor.xiaomi_switch_new
      - sensor.xiaomi_switch_old
      - sensor.yweather_temperature_min
      - sensor.yweather_temperature_max
      - sensor.yw_day3_temperature_min
      - sensor.yw_day2_temperature_min
      - sensor.yw_day1_temperature_min
      - sensor.yw_day3_temperature_max
      - sensor.yw_day2_temperature_max
      - sensor.yw_day1_temperature_max

# View all events in a logbook
# logbook:

# Include iframe in left drawer
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://hassio.local:3218
  terminal:
    title: Terminal
    icon: mdi:console
    url: https://hassio.local:7681

# Log of events
logger:
  logs:
    homeassistant.components: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

weather:
  - platform: yweather

#################################################################################
#                       DEVICES AND INTEGRATIONS                                #
#################################################################################

# Media
media_extractor: # Media extractor, used to cast media with a service

media_player:
#  - platform: spotify
#    client_id: 39edb7ec9c87422784f04f81fc34b6ea
#    client_secret: !secret spotify_api_key

# Notifications
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key

# Hub
rfxtrx:
  device: /dev/ttyUSB0

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    track_new_devices: no
    interval_seconds: 20
    exclude:
      - 192.168.1.30
#  - platform: bluetooth_tracker

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_aqara_key
      mac: 78:11:DC:B7:E4:40

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret


#################################################################################
#                                   INCLUDES                                    #
#################################################################################

binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
