# Weather
- platform: waqi
  token: !secret waqi_api_key
  locations:
    - lille
  stations:
    - Lille Fives, Nord-Pas-de-Calais, France

- platform: mitemp_bt
  mac: '4C:65:A8:D0:D3:36'
  median: 3

- platform: rfxtrx
  automatic_add: False
  devices:
    08200a000000000639:
      name: decteur_co
      fire_event: True

- platform: time_date
  display_options:
    - 'time'

- platform: rest
  resource: https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=disponibilite-parkings&facet=libelle&facet=ville&facet=etat&refine.libelle=Parking+Vieux+Lille
  name: Parking vieux lille
  value_template: '{{ value_json.records[0].fields.dispo }}'
  unit_of_measurement: "places"
  json_attributes:
    - records[0].fields.max
    - records[0].fields.aff
  scan_interval: 300

- platform: rest
  resource: https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=disponibilite-parkings&facet=libelle&facet=ville&facet=etat&refine.libelle=Parking+Nouveau+Siecle
  name: Parking nouveau siècle
  value_template: '{{ value_json.records[0].fields.dispo }}'
  unit_of_measurement: "places"
  json_attributes:
    - records[0].fields.max
    - records[0].fields.aff
  scan_interval: 300

- platform: rest
  resource: https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=vlille-realtime&facet=libelle&facet=nom&facet=commune&facet=etat&facet=type&facet=etatconnexion&refine.commune=SAINT+ANDRE+LEZ+LILLE&refine.nom=ST+ANDRE+MAIRIE
  name: Vlille St André Mairie
  value_template: '{{ value_json.records[0].fields.nbvelosdispo }}'
  unit_of_measurement: "vélos"
  scan_interval: 300

- platform: waze_travel_time
  origin: 50.6634,3.0529699999999593
  destination: 50.6112386,3.1186306
  region: 'EU'
  realtime: true

- platform: scrape
  resource: http://www.programme-tv.net
  name: TF1
  select: "#channel-192 .prog_name"
  attribute: title
  scan_interval: 7200

- platform: scrape
  resource: http://www.programme-tv.net
  name: France 2
  select: "#channel-4 .prog_name"
  attribute: title
  scan_interval: 7200

- platform: scrape
  resource: http://www.programme-tv.net
  name: France 3
  select: "#channel-80 .prog_name"
  attribute: title
  scan_interval: 7200

- platform: scrape
  resource: http://www.programme-tv.net
  name: M6
  select: "#channel-118 .prog_name"
  attribute: title
  scan_interval: 7200

- platform: scrape
  resource: https://www.programme-tv.net/programme/cable-adsl-satellite/
  name: bein1
  select: "#channel-1290 .prog_name"
  attribute: title
  scan_interval: 7200

- platform: scrape
  resource: https://www.programme-tv.net/programme/cable-adsl-satellite/
  name: bein2
  select: "#channel-1304 .prog_name"
  attribute: title
  scan_interval: 7200

- platform: scrape
  resource: https://www.programme-tv.net/programme/cable-adsl-satellite/
  name: bein3
  select: "#channel-1335 .prog_name"
  attribute: title
  scan_interval: 7200

- platform: template
  sensors:
    sunset:
      value_template: "{{as_timestamp(state_attr('sun.sun', 'next_setting'))|timestamp_custom('%Hh%M')}}"
    sunrise:
      value_template: "{{as_timestamp(state_attr('sun.sun', 'next_rising'))|timestamp_custom('%Hh%M')}}"

- platform: miflora
  mac: 'C4:7C:8D:6A:10:47'
  name: mi_flora_1

- platform: miflora
  mac: 'C4:7C:8D:6A:52:91'
  name: mi_flora_2
