# Weather
- platform: waqi
  token: !secret waqi_api_key
  locations:
    - lille
  stations:
    - Lille Fives, Nord-Pas-de-Calais, France
- platform: yweather
  monitored_conditions:
    #- weather_current
    #- temp_min
    #- temp_max
    #- wind_speed
    - humidity
    - temperature
- platform: yweather
  forecast: 1
  name: yw_day1
  monitored_conditions:
    - weather
    - temp_min
    - temp_max
- platform: yweather
  forecast: 2
  name: yw_day2
  monitored_conditions:
    - weather
    - temp_min
    - temp_max
- platform: yweather
  forecast: 3
  name: yw_day3
  monitored_conditions:
    - weather
    - temp_min
    - temp_max
- platform: mitemp_bt
  mac: '4C:65:A8:D0:D3:36'
  median: 3

- platform: rfxtrx
  automatic_add: False
  devices:
    08200a000000000639:
      name: decteur_co
      fire_event: True

- platform: time_date
  display_options:
    - 'time'

# Finance
- platform: coinmarketcap
  currency: Ethereum
  display_currency: EUR

- platform: rest
  resource: https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=disponibilite-parkings&facet=libelle&facet=ville&facet=etat&refine.libelle=Parking+Vieux+Lille
  name: Parking vieux lille
  value_template: '{{ value_json.records[0].fields.dispo }}'
  unit_of_measurement: "places"
  json_attributes: 
    - records[0].fields.max
    - records[0].fields.aff
  scan_interval: 300

- platform: rest
  resource: https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=disponibilite-parkings&facet=libelle&facet=ville&facet=etat&refine.libelle=Parking+Nouveau+Siecle
  name: Parking nouveau siècle
  value_template: '{{ value_json.records[0].fields.dispo }}'
  unit_of_measurement: "places"
  json_attributes: 
    - records[0].fields.max
    - records[0].fields.aff
  scan_interval: 300

- platform: rest
  resource: https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=vlille-realtime&facet=libelle&facet=nom&facet=commune&facet=etat&facet=type&facet=etatconnexion&refine.commune=SAINT+ANDRE+LEZ+LILLE&refine.nom=ST+ANDRE+MAIRIE
  name: Vlille St André Mairie
  value_template: '{{ value_json.records[0].fields.nbvelosdispo }}'
  unit_of_measurement: "vélos"
  scan_interval: 300

- platform: waze_travel_time
  origin: 23 Rue Chanzy, 59350 Saint-André-Lez-Lille
  destination: Rue Chanzy, 59712 Lezennes
  region: 'EU'
  realtime: true
  
- platform: scrape
  resource: http://www.programme-tv.net
  name: TF1
  select: "#channel-192 .prog_name"
  
- platform: scrape
  resource: http://www.programme-tv.net
  name: France 2
  select: "#channel-4 .prog_name"

- platform: scrape
  resource: http://www.programme-tv.net
  name: France 3
  select: "#channel-80 .prog_name"
  
- platform: scrape
  resource: http://www.programme-tv.net
  name: M6
  select: "#channel-118 .prog_name"

# Flower power
#- platform: flower_power
#  username: rojowstyle@gmail.com
#  password: !secret flower_power_pwd
#  clientid: rojowstyle@gmail.com
#  clientsecret: !secret flower_power_token
