- platform: rfxtrx
  automatic_add: False
  devices:
    "0710090041010000":
      name: canape
    "0710090041020000":
      name: salon
    "0710090044030000":
      name: guirlande
    "0710090041040000":
      name: table
    0b1100310184c6da01010f80:
      name: dio1
    0b1100350184c6da02010f70:
      name: dio2
    0b1100360184c6da03010f70:
      name: dio3
    "0710090041050000":
      name: zapO313-1
    "0710090041060000":
      name: zapO313-2
    "0710090043070000":
      name: zapO313-3
    "0710090043080600":
      name: zapO313-4
    "0710090043090500":
      name: zapO313-5


- platform: broadlink
  host: 192.168.1.11
  mac: '34:ea:34:8e:ef:f0'
  type: rm_mini
  timeout: 15
  switches:
    tv:
      friendly_name: "Télé du salon"
      command_on: 'JgBoAAABKI8VERURFRAVERURFREUERURFTUVNBU1FTUVNBU1FTUVERUQFTUVERU0FREVERURFRAVNRURFTQVERU1FTUVNBU1FQAFGwABKEcVAAw2AAEoRxUADDcAASdHFQAMNwABJ0gUAA0F'
      command_off: 'JgBoAAABKI8VERURFRAVERURFREUERURFTUVNBU1FTUVNBU1FTUVERUQFTUVERU0FREVERURFRAVNRURFTQVERU1FTUVNBU1FQAFGwABKEcVAAw2AAEoRxUADDcAASdHFQAMNwABJ0gUAA0F'
